### ISSUE TITLE
Could not install beta 4

### ISSUE THREAD

**Issue by vectah0** [openhab/openhab-qnap-qpkg#1]
Error	2016/09/24	20:34:57	System	127.0.0.1	localhost	openHAB 2.0.0-b4-1 installation failed. Data file error.	

btw I can install b3 without any problems

(TS-451+ (QTS 4.2.2))

**Comment by thopiekar** [comment]
Ok, that's strange. (Got an older QTS here.)
The difference between b3 and b4 is that I don't need to repack the zip anymore as openhab comes with it's own tar.gz's now.
Which install mode do you use? Are you using a share called "openHAB"?

Thanks

**Comment by thopiekar** [comment]
The problem is at the moment, that I'm running the OH2 snapshot, so I can't test it without breaking my installation. It is possible to get more detailed error messages?

**Comment by Stefan39135** [comment]
i get the same error - Data file error - on my SS-439 Pro (QTS 4.2.2), how can I help you to finde the Problem, I can install b3 without any problems

**Comment by MountAthos** [comment]
Just in case you want to see
Error	2016/09/30 openHAB 2.0.0-b4-1 installation failed. Data file error.
QNAP 212P (Dual Bay) with 4.2.2 FW

**Comment by Jeffmong** [comment]
I have the same issue on my TS-1279U-RP, b3 works fine, b4 fails with the Data file error.
Your "package_routines" file in b4 at line 143 still references "openhab-online-2.0.0.b3.tar.gz"
Changed to "openhab-online-2.0.0.b4.tar.gz", repackaged and install completed successfully.

**Comment by thopiekar** [comment]
You are so right :eyes: (face-palmed about that here..)

**Comment by thopiekar** [comment]
I only wonder how I can make the script at this place more generic, so I won't forget to change it again next time.

**Comment by thopiekar** [comment]
Thank you for the hint @Jeffmong !
Just released `2.0.0-b4-2`. Any feedback is welcome :wink:

**Comment by cniweb** [comment]
Hi @thopiekar,

can you contact me, please (see my profile)?

Thanks,
Chris

**Comment by thopiekar** [comment]
@cniweb Of course I can.
Check your inbox 😉
