### ISSUE TITLE
openHAB 2.0 beta5 has been released

### ISSUE THREAD

**Issue by Stefan39135** [openhab/openhab-qnap-qpkg#11]
how is it possible to upgrade the beta4 installation?

Stefan

**Comment by thopiekar** [comment]
Sorry @Stefan39135, I just had to less time recently to prepare for the beta 5.
I had different changes in my own openhab.sh, which I merged now into the repository here now.

The updated packages for beta 5 (online and offline version) shall be uploaded soon.

**Comment by thopiekar** [comment]
New QPKGs are at: https://github.com/openhab/openhab-qnap-qpkg/releases
