### ISSUE TITLE
How to 'upgrade' from b4 version to b5 ?

### ISSUE THREAD

**Issue by MartinW2** [openhab/openhab-qnap-qpkg#13]
First of all: Thanks a lot for providing a QNAP distro of OpenHAB! I am happy running it and will continue using it.
I am currently running version 2.0.0.b4 on my QNAP TS212, along with JRE_ARM 8.65.0.
How should I 'upgrade' to version b5 ? 
I guess I should not deinstall and run the installation description right from the beginning, in order not to lose my current configuration.
- will b5 still be happy with JRE_ARM 8.65.0 ?
- should i simply 'overwrite' the files of the package via SSH ?
Any hints are appreciated.
Martin

**Comment by RalphPungaKronbergs** [comment]
+1

Would be great to know how to update/upgrade openHAB if installed as qpkg

**Comment by thopiekar** [comment]
Duplicate to #14
