### ISSUE TITLE
How to 'upgrade' from b5 version final ?

### ISSUE THREAD

**Issue by Stefan39135** [openhab/openhab-qnap-qpkg#14]
can you please build the qpkg for the final OpenHab 2.0

stefan

**Comment by thopiekar** [comment]
Like in #13 : 
Just install the new QPKG, like on the first installation.
I strongly recommend to stop the openHAB service before installing the new QPKG via SSH. openHAB still misses a start/stop mechanism, which waits until the start/stop is completely done.
That means if you update openHAB with the latest QPKG without doing that it might try to install the new files over a running session.

Regards

PS: The new release will be uploaded soon.

**Comment by thopiekar** [comment]
Updating should now easily work as long as openHAB has really been stopped before.
