### ISSUE TITLE
Error in installation guide

### ISSUE THREAD

**Issue by mortenbirkelund** [openhab/openhab-qnap-qpkg#18]
I dont know if this is the correct place, but i think i found an error in the installation guide of this page:
http://docs.openhab.org/installation/qnap.html

It says that the shared folder should be called "openHAB2", but in the readme file here on githup it says that the shared folder should be called "openHAB" (without 2). It took my some time to find, but when i installed openhab on my qnap with only a shared folder called "openHAB2" then i couldnt find the configuation files and folders. Then i uninstalled it, and created a shared folder called "openHAB" (so that i had both) and once i reinstalled openhab then the configuations file was created in the shared folder called "openHAB"

**Comment by sbeccato** [comment]
Same issue for me (on QNAP TS-469L), solved as described by mortenbirkelund.

Please fix the installation guide!

**Comment by GoRo33** [comment]
1+ for me. 
In my installation it was thisame.

**Comment by k0ssi** [comment]
`QPKG_NAME="openHAB"
QPKG_ROOT=`/sbin/getcfg $QPKG_NAME Install_Path -f ${CONF}`
QPKG_DISTRIBUTION=${QPKG_ROOT}/distribution`

this happens cause path and distribution path is build from QPKG name which is named to "openHAB".

**Comment by dsanow92** [comment]
This still didn't work for me. I am trying to install OpenHab_2.1.0_x86_64.qpkg and I have tried both share folders "openHAB2" and "openHAB" but still not installing to the correct folder. #38

I am using a TS-251+ running software version 4.3.3.0396 Build 20171205

**Comment by 6r15u** [comment]
http://docs.openhab.org/installation/qnap.html has now correct folders.
I also created a pull request fot the documentation within this git

**Comment by thopiekar** [comment]
Great work @6r15u !
I send you an invite to join the team! 👍

**Comment by jstimmer** [comment]
@6r15u 
Please also update the uninstall verbiage toward the bottom of the http://docs.openhab.org/installation/qnap.html installation guide
