### ISSUE TITLE
i want to connect to openhab cloud but it want

### ISSUE THREAD

**Issue by badplay** [openhab/openhab-qnap-qpkg#22]
i installed openhab cloud under misc and now i want to open an account at myopencloud.com but were i find the uuid and the secret

**Comment by thopiekar** [comment]
You need to login to your NAS via SSH and go to the location where openHAB has been installed. There you will find the distribution directory with all contents.

Regards

**Comment by bezibaerchen** [comment]
I fear this wouldn't help anyway as at least for me the shipped version of java doesn't work

**Comment by thopiekar** [comment]
Well, @badplay was asking here the UUID and the secret is, not whether it will work or not.
In addition to that the service script (opnehab.sh) is able to download a more recent version, therefore if he is able to get there, he can also make the addon working with a more recent java version easily.

**Comment by bezibaerchen** [comment]
Ah okay, wasn't aware of this. Will execute it myself right away. Just switched to trying to run it on the QNAP yesterday as my RaspBi mmc died. Looking good, however, it's dying after a couple of hours, but let's see. Sorry for causing confusion.

**Comment by thopiekar** [comment]
@bezibaerchen No problem :smile: 

Since I got no answer from @badplay I guess he found the files and got it working..
