### ISSUE TITLE
Make required firmware clear

### ISSUE THREAD

**Issue by peelos** [openhab/openhab-qnap-qpkg#24]
Thanks for a great initiative. What is not clear is which QNAP firmware is required, proposal to add this to the readme file.

**Comment by mjohenneken** [comment]
As I first came across your issue while searching for experiences with OH + QNAP, do you know which firmware version is required ?

**Comment by peelos** [comment]
Hi, I do know that for me it is working on the latest 4.3.3, hope that
helps.

**Comment by mjohenneken** [comment]
okay i have QTS 4.2.5 i seems to be latest for my QNAP system. I will 
test if it works.Tough, a minimum required Version or at least RAM CPU 
requirements would be helpful in the docs.

Max Johenneken
Software Entwickler
anderScore feiert sein 11-jähriges Jubiläum

anderScore GmbH
Frankenwerft 35
50667 Köln
Deutschland
www.anderScore.com <BLOCKED::http://www.anderscore.com/>

Tel.: +49 (221) 3558 35341
Fax.:        +49 (221) 3558 3531
Mobile:     +49 (151) 64 04 89 18
Email: max.johenneken@anderScore.com <mailto:max.johenneken@anderScore.com>

Geschäftsführung:    Sibylle Ohm
Handelsregister:       Amtsgericht Köln, HRB 56533

**Comment by thopiekar** [comment]
The RAM requirements are always the same. I personally bought a TS-228 since it has 1GB of RAM. A lot of QNAP devices for "home use" only have have 0.5GB, which is too less, if you want to run other software as well.

**Comment by peelos** [comment]
I updated to QTS 4.3.3 0305 and openhab 2.0.0.2 was no longer accessible via webgui and had to install 2.0.0-3 to fix

**Comment by 6r15u** [comment]
As I only have 1 QNAP NAS, I can only make the package for that firmware version. 
Nevertheless I think the config file says: QTS_MINI_VERSION="4.1.0"

I'll add this to the readme, is that solution ok with you, @peelos ?
If yes, I would close this issue after your confirmation

**Comment by 6r15u** [comment]
@mjohenneken 
> at least RAM CPU requirements would be helpful in the docs
For me, the raw installation takes about 200MB of RAM. I don't know how QTS can handle swaps as the service doesn't need high speed. This would make sense, but I'm too less into the architecture of QTS.
I think CPU requirements are so low that noone should run into trouble.

Nevertheless I will make a hint in the readme that people should be aware of this

**Comment by thopiekar** [comment]
I agree. But RAM is more critical. Normally you don't use the core functionality of openHAB and QTS's services. Thus, is you want to use your NAS normally (syncing data, using it as an mediaserver) and use Z-Wave and other smarthome bindings, you need (at least!) 1GB of RAM.
This is what I personally recommend. Otherwise you get into trouble, when multiple processes are running at one time and consume so many ran that one of those gets out of ram.
Therefore you get crashes of side functionalities and misbehaviours either in openHAB or QTS.

**Comment by 6r15u** [comment]
Thanks for the info. Never used Z-Wave bindings. Only have homematic. But 1GB of RAM seem a lot to me. Is Java so lame?

**Comment by peelos** [comment]
Sure. Thanks
