### ISSUE TITLE
Inaccuracy in installation description

### ISSUE THREAD

**Issue by Hukuma23** [openhab/openhab-qnap-qpkg#26]
openHAB2 doesn't use openHAB2 shared folder for addons, configurations and userdata, it using openHAB (without "2"). Please fix this in installation manual. Thank you.

**Comment by maydo** [comment]
i can confirm this, was also confused, tried reinstalling many times.

The Share or the folder must be named to "openHAB"

**Comment by shorthander** [comment]
same here...

**Comment by 6r15u** [comment]
documentation updated
