### ISSUE TITLE
Java not enabled! on 2.2.0-1 after installation

### ISSUE THREAD

**Issue by melinko** [openhab/openhab-qnap-qpkg#41]
I'm on Firmware 4.3.4.0435 on my TS-451
Since the 2.2.0 Package i get this error message right after the installation finished. 
"Java not enabled! Please read the documentation about details.	"
I did a clean install and confirmed that all "openHAB" folders where empty or deleted. 
The installation of the old 2.1.0 package still works fine, except that it does not use the shared folder as an install path.
I tried to look for logs or anything, but the /userdata consists only of the folders /etc and /tmp nothing more. 
Did something about the JRE change in 2.2.0? Or am I missing something big here? 
I'm kind of clueless why the 2.1.0 works just fine but the 2.2.0 does not.

**Comment by 6r15u** [comment]
Oh, It could be you need to make a Java update. Somewhere I read, that OH2.2.0 needs at least 1.8.101
If you have the JRE_ARM package installed, you can uninstall it and then install the JRE package. That has 1.8.151 and works fine for me

**Comment by thopiekar** [comment]
Well, I would say that Java is not installed at all. The QPKG does not depend on any JRE package (https://github.com/openhab/openhab-qnap-qpkg/blob/master/qpkg.cfg#L18), because the QNAP packages for them was not up to date and I added to the service script a installation procedure to install a more recent version manually.
Therefore the user does not really depend on a JRE package, but can decide which JRE to take.
The freedom has been made, because you need new certificate definitions for myopenhab, which comes with more recent JRE versions.

**Comment by melinko** [comment]
oh.. my bad...
Thanks for the hint... After installation of the current JRE 8.151.2 it works just fine.
And just to clarify the 2.1.0 did not depend on any JRE being installed? Because that one just worked fine.
Thanks a lot.

**Comment by thopiekar** [comment]
Well, we are leaking a good documentation at this point. 2.1.0 also depends on a JRE installation. You most likely installed it in the past via service script and during update it gets removed together with openHAB itself ( that is intended and shall prevent creating data mess ).

**Comment by 6r15u** [comment]
Does the script automatically install Java?
I thought the openHAB.sh script checks for it an then reports an error. Only if I trigger Java install by console Java is installed, nor?

**Comment by thopiekar** [comment]
Nope, the script is not installing it on its own, because you have to agree to Oracle's Java licence. So whenever the script can't find Java installed neither by QNAPs App Store nor via script, then it is showing the error message @melinko mentioned.
