### ISSUE TITLE
cannot access /dev/ttyACM0 - permissions issue

### ISSUE THREAD

**Issue by mishakim** [openhab/openhab-qnap-qpkg#43]
I installed the package with no problem, but when trying to use Z-wave with the Gen 5 Z-stick, I installed the cdc-acm.ko driver and see the stick at /dev/ttyACM0, but when I point the Thing to that port, I get 
`2018-01-13 11:23:58.965 [hingStatusInfoChangedEvent] - 'zwave:serial_zstick:5bec0518' changed from OFFLINE (BRIDGE_OFFLINE): Controller is offline to OFFLINE (COMMUNICATION_ERROR): Serial Error: Port /dev/ttyAMC0 does not exist`
The usual explanation / fix for this is permissions, specifically, adding user openhab to group dialout, however, I don't have that group, and when I "ls -l /dev/ttyACM*", I get this: 
`[misha@homeNAS ~]$ ls -l /dev/ttyACM*                                 
crw-rw---- 1 admin administrators 166, 0 2018-01-13 09:57 /dev/ttyACM0`

It seems like creating a group dialout wouldn't work, since the system obviously isn't configured to assign tty devices to that group. Just adding user openhab to the administrators group that does seem to own the tty devices didn't work either (and doesn't seem like a good idea).  What else should I try?

I'm running 4.3.3 build 20171117, and using the 2.2.0 openhab package.

**Comment by mishakim** [comment]
I'm an idiot and missed the typo. Fixing that resolved it, though now I'm not sure if my messing with permissions mattered or not.

**Comment by thopiekar** [comment]
Don't worry. Since openHAB is executed under admin rights, we don't face these issues.
