### ISSUE TITLE
timezone is not set

### ISSUE THREAD

**Issue by Andy1402** [openhab/openhab-qnap-qpkg#8]
Hi.
I'm from Germany and we have winter time, now. But in OpenHAB there is shown the old summer time. NTP ist working well and my QNAP NAS is working with the correct winter time, too. 

I found the solution for this. It is necessary to add the following line to openHAB.sh:
export TZ=`/sbin/getcfg System "Time Zone" -f /etc/config/uLinux.conf`

It's working fine in my case.

Regards.
Andy

**Comment by thopiekar** [comment]
Me, too. I commented on your PR. Thanks again!
